version: '2'
services:
  app:
    build: .
    links:
      - graylog
      - rabbit
    environment:
      - RABBIT_HOST=rabbit
      - RABBIT_PORT=5672
      - RABBIT_USER=guest
      - RABBIT_PASSWORD=guest
      - RABBIT_QUEUE=logs
      - GRAYLOG_HOST=graylog
      - GRAYLOG_PORT=12201
    stdin_open: true
    tty: true

  mongo:
    image: "mongo:3"

  elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"

  graylog:
    image: graylog2/server:2.1.1-1
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
    links:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"
      - "12201/udp:12201/udp"
      - "12201/tcp:12201/tcp"
      - "1514/udp:1514/udp"

  rabbit:
    image: rabbitmq:3-management
    stdin_open: true
    tty: true
    ports:
      - 15672:15672
      - 5672:5672
